using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WGU_C968_1_v001
{
    public class InHousePart : Part
    {
        private int machID;
        public int MachineID { get; set; }

        public InHousePart() { }

        //public InHousePart(int ID, string name, double price, int stock, int max, int min)
        //{
        //    PartID = ID;
        //    Name = name;
        //    InStock = stock;
        //    Price = price;
        //    Max = max;
        //    Min = min;
        //}

        public InHousePart(
            int ID,
            string name,
            double price,
            int stock,
            int max,
            int min,
            int machID
        )
        {
            PartID = ID;
            Name = name;
            InStock = stock;
            Price = price;
            Max = max;
            Min = min;
            MachineID = machID;
        }

        // Generated by VS?
        public override bool Equals(object obj)
        {
            return obj is InHousePart part
                && PartID == part.PartID
                && Name == part.Name
                && Price == part.Price
                && InStock == part.InStock
                && Min == part.Min
                && Max == part.Max
                && machID == part.machID
                && MachineID == part.MachineID;
        }

        public override int GetHashCode()
        {
            int hashCode = -1900385863;
            hashCode = hashCode * -1521134295 + PartID.GetHashCode();
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(Name);
            hashCode = hashCode * -1521134295 + Price.GetHashCode();
            hashCode = hashCode * -1521134295 + InStock.GetHashCode();
            hashCode = hashCode * -1521134295 + Min.GetHashCode();
            hashCode = hashCode * -1521134295 + Max.GetHashCode();
            hashCode = hashCode * -1521134295 + machID.GetHashCode();
            hashCode = hashCode * -1521134295 + MachineID.GetHashCode();
            return hashCode;
        }
    }
}
